from __future__ import annotations
from typing import Protocol, Tuple, Optional
import numpy as np


class Laser(Protocol):
    def lock_to_wavelength_nm(self, wl_nm: float) -> None: ...
    def set_scan_speed(self, speed: float) -> None: ...
    def start_scan(self, direction: str) -> None: ...
    def stop_scan(self) -> None: ...
    def close(self) -> None: ...


class Wavemeter(Protocol):
    def get_wavelength_nm(self) -> float: ...
    def close(self) -> None: ...


class DetectorCounts(Protocol):
    """Return a single integer count for an exposure window."""
    def acquire_counts(self, exposure_s: float) -> int: ...
    def close(self) -> None: ...


class DetectorSpectrum(Protocol):
    """Return (axis, intensity) for an exposure window."""
    def set_exposure(self, exposure_s: float) -> None: ...
    def acquire_spectrum(self) -> Tuple[np.ndarray, np.ndarray]: ...
    def close(self) -> None: ...


class PowerMeter(Protocol):
    def read_power_W(self) -> float: ...
    def close(self) -> None: ...
